version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "PR: dependencies"
    open-pull-requests-limit: 15
    groups:
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "PR: dependencies"
    groups:
      "actions/cache":
        patterns:
          - "actions/cache/*"
